"""Generates static/css/tokens.css from the one palette that is the source of truth.

tokens.css holds values. primitives and templates hold references only. Raw hex in
the system layer fails review, so the only place hex appears is this file and the
generated output.
"""
from pathlib import Path

DARK = {
    "bg": "#0d0d0f", "surface": "#131316", "surface-low": "#1a1a1e",
    "surface-container": "#212126", "surface-high": "#2b2b31", "surface-highest": "#36363d",
    "text": "#e8e8ea", "text-dim": "#9aa0a6", "text-muted": "#80858d",
    "accent": "#f2f2f4", "on-accent": "#0d0d0f",
    "border-divider": "#26262b", "border-rest": "#33333a", "border-strong": "#4a4a53",
    "danger": "#ef4444", "warn": "#f5b942", "ok": "#4ade80",
}
LIGHT = {
    "bg": "#f4f4f6", "surface": "#ffffff", "surface-low": "#eeeef1",
    "surface-container": "#e7e7ea", "surface-high": "#dcdce1", "surface-highest": "#d0d0d7",
    "text": "#16161a", "text-dim": "#3d424a", "text-muted": "#525862",
    "accent": "#16161a", "on-accent": "#f4f4f6",
    "border-divider": "#e0e0e5", "border-rest": "#cfcfd6", "border-strong": "#9b9ba6",
    "danger": "#c62026", "warn": "#8a5300", "ok": "#0f6b3a",
}
GLASS_DARK = {
    "glass-fill": "rgba(54,54,61,.72)", "glass-edge-top": "rgba(255,255,255,.20)",
    "glass-edge-bottom": "rgba(255,255,255,.04)", "glass-spec": "rgba(255,255,255,.24)",
    "glass-shadow": "0 8px 32px -8px rgba(0,0,0,.55)", "ground": "rgba(255,255,255,.055)",
    "scrim-partial": "rgba(13,13,15,.32)",
}
GLASS_LIGHT = {
    "glass-fill": "rgba(255,255,255,.68)", "glass-edge-top": "rgba(255,255,255,.90)",
    "glass-edge-bottom": "rgba(0,0,0,.08)", "glass-spec": "rgba(255,255,255,.90)",
    "glass-shadow": "0 4px 20px -6px rgba(0,0,0,.14)", "ground": "rgba(255,255,255,.95)",
    "scrim-partial": "rgba(244,244,246,.32)",
}
SPACE = [2, 4, 6, 8, 12, 16, 20, 24, 32, 40, 48, 64]
RADIUS = {"sm": "6px", "md": "10px", "lg": "16px", "xl": "22px", "pill": "999px"}

# Layout metrics. These belong here for the same reason colours do: a magic number
# repeated across a stylesheet and a media query drifts apart the first time one of
# them is edited alone.
METRIC = {
    "rail": "72px",          # desktop nav rail
    "pane": "336px",         # meetings list pane
    "tabbar": "60px",        # mobile bottom tab bar
    "player": "72px",        # sticky audio bar
    "reading": "68ch",       # prose measure
}


def block(colors, glass, indent="  "):
    out = [f"{indent}--{k}: {v};" for k, v in colors.items()]
    out += [f"{indent}--{k}: {v};" for k, v in glass.items()]
    return "\n".join(out)


def build() -> str:
    space = "\n".join(f"  --space-{n}: {n}px;" for n in SPACE)
    radius = "\n".join(f"  --radius-{k}: {v};" for k, v in RADIUS.items())
    metric = "\n".join(f"  --{k}: {v};" for k, v in METRIC.items())
    return f"""/* Generated by tools/gen_tokens.py. Do not edit by hand. */

:root {{
{block(LIGHT, GLASS_LIGHT)}

{space}
{radius}
{metric}

  --font-prose: Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  --font-mono: "JetBrains Mono", ui-monospace, SFMono-Regular, monospace;
  --ease: cubic-bezier(0.2, 0, 0, 1);
  --dur-micro: 120ms;
  --dur-panel: 200ms;
  --dur-fold: 320ms;
}}

@media (prefers-color-scheme: dark) {{
  :root:not([data-theme="light"]) {{
{block(DARK, GLASS_DARK, "    ")}
  }}
}}

:root[data-theme="dark"] {{
{block(DARK, GLASS_DARK, "    ")}
}}
"""


if __name__ == "__main__":
    target = Path(__file__).resolve().parent.parent / "src/static/css/tokens.css"
    target.write_text(build())
    print(f"wrote {target}")
